### ISSUE TITLE
my pawn.cmd why not work?

### ISSUE THREAD

**Issue by sa-mp-kr** [katursis/Pawn.CMD#31]
![image](https://user-images.githubusercontent.com/13404285/102931657-1b860e00-44e2-11eb-8ebb-6b50150d6e8e.png)
![image](https://user-images.githubusercontent.com/13404285/102931690-2b9ded80-44e2-11eb-929f-69d0a32427b5.png)
![image](https://user-images.githubusercontent.com/13404285/102931754-4d977000-44e2-11eb-828f-117b2cc47259.png)

i try used pawn.cmd include but is not work!
and OnPlayerCommandText working fine but pawn.cmd doesn't work

![image](https://user-images.githubusercontent.com/13404285/102931823-728be300-44e2-11eb-81d5-85e84b9f2557.png)

my include version ▽
[YSI] version 4.00.0001 ( If you use the latest version, a compilation error occurs. )
[Pawn.CMD]  version  v3.3.3

**Comment by DawkinNguyen** [comment]
SOLVED.
Just delete every OnPlayerCommandText in the gamemodes.

**Comment by sa-mp-kr** [comment]
> ![image](https://user-images.githubusercontent.com/13404285/102931657-1b860e00-44e2-11eb-8ebb-6b50150d6e8e.png)
> ![image](https://user-images.githubusercontent.com/13404285/102931690-2b9ded80-44e2-11eb-929f-69d0a32427b5.png)
> ![image](https://user-images.githubusercontent.com/13404285/102931754-4d977000-44e2-11eb-828f-117b2cc47259.png)
> 
> i try used pawn.cmd include but is not work!
> and OnPlayerCommandText working fine but pawn.cmd doesn't work
> 
> ![image](https://user-images.githubusercontent.com/13404285/102931823-728be300-44e2-11eb-81d5-85e84b9f2557.png)
> 
> my include version ▽
> [YSI] version 4.00.0001 ( If you use the latest version, a compilation error occurs. )
> [Pawn.CMD] version v3.3.3
