### ISSUE TITLE
[Pawn.CMD] HandleCommand

### ISSUE THREAD

**Issue by Kripteks** [katursis/Pawn.CMD#34]
[Pawn.CMD] HandleCommand: Call: amx_Exec(struct tagAMX *:02F3EF70, int *:0019F760, int:679): Array index out of bounds (4)
help me

**Comment by alexmarkel0v** [comment]
do you fix this? i have the same problem

**Comment by alexmarkel0v** [comment]
oh whoa, my problem is that because i'm an idiot, sorry

**Comment by Kripteks** [comment]
Problem solved.
