### ISSUE TITLE
Will there be a version that supports open.mp?

### ISSUE THREAD

**Issue by duydang2311** [katursis/Pawn.CMD#40]
Hello,
Pawn.CMD has been my favourite command processor for years and I have never had any problems with this great plugin. The flag and alias features of this just come in very handy and useful.
Since I heard that open.mp would not be compatible with Pawn.CMD because of the memory hacking in this plugin, I'm curious if there would be a compatible version for open.mp in the future? Otherwise, I would have to migrate to another command processor as I'm likely to move to open.mp soon.

**Comment by katursis** [comment]
https://github.com/katursis/Pawn.CMD/tree/omp
