### ISSUE TITLE
[Pawn.CMD] DoAmxLoadImpl: Mismatch between the plugin (3.4.0) and include (3.3.6) versions

### ISSUE THREAD

**Issue by plakapenka** [katursis/Pawn.CMD#56]
при всём уважении, ты вообще проверяешь что заливаешь в релизы?

это уже который раз.

1. Инклюды в windows и linux архивах разные.
2. Они оба не работают)
3. Ошибки в консоли аля  Skipping legacy plugin 'pawnraknet'; тянутся уже ~5 версий

**Comment by katursis** [comment]
🤦

1. Они полностью идентичные, релиз собирает автоматика.
2. Оба работают. Судя по тексту ошибки, проблема в том, что ты забыл пересобрать свой скрипт с новой версией инклуда.
3. Потому что ты положил плагин в папку plugins, а не components, как того требует omp.

В следующий раз перед наездом перепроверь за собой.

**Comment by plakapenka** [comment]
![image](https://user-images.githubusercontent.com/10694250/219035210-a7f302e5-0d3d-45f0-867c-ca518be79b08.png)

Ок, возможно они одинаковые, я судил по размеру.

Все остальное актуально. Я не забыл пересобрать скрипт. И плагины лежат там где надо ( в components ). Человек в issue ниже пишет тоже самое
